// <auto-generated />
namespace MigrationsDemo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddPostAbstract : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPostAbstract));
        
        string IMigrationMetadata.Id
        {
            get { return "201305311859585_AddPostAbstract"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
