// <auto-generated />
namespace MigrationsDemo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddPublishDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPublishDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201305311902351_AddPublishDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
